services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    enviroment:
      - .env   # Load Postgres env vars from .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: api_service:latest
    container_name: api_service
    restart: always
    enviroment:
      - .env   # App also loads from same .env
    ports:
      - "8000:8000"
    command: python3 run.py